-- Color Comparison Script
-- Shows the color mapping for USDC conversion

print("=== USDC Color Conversion ===")
print("")
print("Original Aavegotchi-Gen0-Front-Body-ETH.svg colors:")
print("  Dark purple:  #64438e")
print("  Light purple: #edd3fd") 
print("  White:        #fff")
print("")
print("USDC (maUSDC) color scheme:")
print("  Primary:      #2664ba (blue)")
print("  Secondary:    #d4e0f1 (light blue)")
print("  Cheek:        #f696c6 (pink)")
print("")
print("Color mapping:")
print("  #64438e → #2664ba (dark purple → blue)")
print("  #edd3fd → #d4e0f1 (light purple → light blue)")
print("  #fff    → #fff    (white stays white)")
print("")
print("Output file: output/body_00_maUSDC.aseprite")
print("Rendered: 3803 pixels on 64x64 canvas")
print("")
print("Conversion completed successfully!")
